### ISSUE TITLE
Membuat tombol pesanan diterima ketika pengiriman barang

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#116]
![pesanan diterima](https://user-images.githubusercontent.com/46917596/75636519-0a69c900-5c52-11ea-840b-b4f6e195e27f.png)

**Comment by masbrodev** [comment]
@masbrodev 

Apacan Engkok Lah

**Comment by masbrodev** [comment]
selesai

**Comment by milhamsuryapratama** [comment]
PR dari branch refactor/transaksi saya merge dulu, perubahan minor nya bisa dilihat disini

https://github.com/commitunuja/mpnj-web/pull/160#issuecomment-603135543
https://github.com/commitunuja/mpnj-web/pull/160#issuecomment-604316336
