### ISSUE TITLE
Pengelompokan Transaksi dan Refactor data di halaman detail pesanan

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#149]
@masbrodev

**Comment by masbrodev** [comment]
Pull Request Pada #151

**Comment by masbrodev** [comment]
![Screenshot (119)](https://user-images.githubusercontent.com/37744914/77112474-a4f04780-6a5b-11ea-9d77-0e1546891529.png)

**Comment by milhamsuryapratama** [comment]
Good Job.
