### ISSUE TITLE
Load data rekening admin dari database di halaman konfirmasi data

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#155]
![konfirmasi data](https://user-images.githubusercontent.com/46917596/77172604-cf401480-6af0-11ea-8f00-d7a9c657d555.png)

Data rekening admin pada halaman konfirmasi data masih manual, harusnya data rekening admin mengambil dari database rekening admin.

**Comment by masbrodev** [comment]
mon mareh berrik keterangan @LuthfiRobit

**Comment by LuthfiRobit** [comment]
Sudah dikerjakan sayang 🤪
