### ISSUE TITLE
Validasi ketika status sudah bayar di halaman checkout sukses dan konfirmasi data

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#158]
Validasi itu dilakukan untuk mencegah user yang sudah melakukan konfirmasi pembayaran akan melakukan konfirmasi lagi.

![image](https://user-images.githubusercontent.com/46917596/77337115-0a458080-6d5b-11ea-9a5e-11ae87b2f5f5.png)

Jadi kalau status nya sudah bayar, ketika user mengunjungi halaman checkout sukses atau konfirmasi bayar, harus di redirect kembali ke halaman pesanan atau munculkan notifikasi kalau kode transaksi ini sudah melakukan konfirmasi pembayaran.

![image](https://user-images.githubusercontent.com/46917596/77337263-411b9680-6d5b-11ea-9587-3b40caa19449.png)

Contoh, kode transaksi diatas sudah melakukan konfirmasi bayar, tapi dia masih bisa mengunjungi halaman konfirmasi.

**Comment by LuthfiRobit** [comment]
sudah selesai
