### ISSUE TITLE
Menambah batas waktu pembayaran pada transaksi

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#163]
Batas waktu pembayaran berguna untuk memberi batas pada pembeli untuk membayar.

Contoh pembeli membeli barang tanggal 1, jadi batas pembayaran nya bisa 24 jam dari waktu pesan.

Jika pembeli tidak melakukan konfirmasi pembayaran sampai batas waktu yang telah di tentukan, maka transaksi secara otomatis akan dibatalkan.

**Comment by LuthfiRobit** [comment]
I'll try dude

**Comment by milhamsuryapratama** [comment]
kau sudah nambah field batas pembayaran belum di tabel transaksi ? kok sudah bikin scheduler aja

**Comment by LuthfiRobit** [comment]
beh salah sangka

**Comment by milhamsuryapratama** [comment]
kerjain satu satu

1. tambah field batas pembayaran di tabel transaksi
2. ketika pembeli membuat pesanan, data batas pembayaran di ambil dari tanggal transaksi ditambah 1 hari

kalau itu sudah bisa, netx task yang lain nya (cron job)

**Comment by LuthfiRobit** [comment]
oke oke 
mana dulu ni validasi di transaksi apa ini dulu nih yg urgent?

**Comment by milhamsuryapratama** [comment]
yang batas waktu saja dulu

**Comment by LuthfiRobit** [comment]
ini sudah @milhamsuryapratama
