### ISSUE TITLE
Ubah card produk di halaman pelapak

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#170]
![image](https://user-images.githubusercontent.com/46917596/77948746-1350c780-72f0-11ea-82fb-e32398c437a2.png)

ubah tampilan card produk pada halaman pelapak. samakan tampilan card produk nya seperti pada halaman home atau halaman produk

**Comment by LuthfiRobit** [comment]
Sapa garap ini? @milhamsuryapratama @masbrodev

**Comment by milhamsuryapratama** [comment]
> Sapa garap ini? @milhamsuryapratama @masbrodev

Sudah di PR sama @masbrodev

**Comment by milhamsuryapratama** [comment]
https://github.com/commitunuja/mpnj-web/pull/171

**Comment by LuthfiRobit** [comment]
> > Sapa garap ini? @milhamsuryapratama @masbrodev
> 
> Sudah di PR sama @masbrodev

Boh okedah kalo begitu
