### ISSUE TITLE
LIST EKSPEDISI (KURIR) DI TOKO

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#240]
menambah list ekspedisi di profil pelapak
-tambah database
-crud di bagian seller.belanj
-tampilkan di mpnj-web

**Comment by milhamsuryapratama** [comment]
ini sudah sampek mana progress nya @LuthfiRobit ?

**Comment by LuthfiRobit** [comment]
Masih new brance... Fokus ke checkout sek min
