### ISSUE TITLE
VALIDASI UNPLOAD FILE

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#255]

**Comment by milhamsuryapratama** [comment]
ini validasi upload file dibagian apa ? di upload file struk dan foto profile sudah ada validasinya deh

**Comment by LuthfiRobit** [comment]
kalo dak salah dibagian api

**Comment by milhamsuryapratama** [comment]
> kalo dak salah dibagian api

dibagian api apa ?
