### ISSUE TITLE
Filter produk berdasarkan popularitas

### ISSUE THREAD

**Issue by milhamsuryapratama** [commitunuja/mpnj-web#69]
Di halaman produk, terdapat filter produk berdasarkan popularitas. Tinkat popularitas dapat dihitung dari rating atau jumlah terjual dari sebuah produk. Jadi ketika dilakukan sorting berdasarkan popularitas, maka produk akan di urutkan berdasarkan rating tertinggi atau jumlah terjualnya yang paling banyak

**Comment by masbrodev** [comment]
@masbrodev 

saya coba dulu

**Comment by masbrodev** [comment]
Belum Sempurna

**Comment by milhamsuryapratama** [comment]
Sempurnakan
